### ISSUE TITLE
Auth MVP

### ISSUE THREAD

**Issue by bmzhu2** [bmzhu2/StrifeCloud#2]
One note in regard to the checklist you posted on slack:

-SoundCloud's home button with logo does not take you to "/" if you are logged in (it will if you are not logged in however)

**Comment by evhumphrey** [comment]
Hey, looks good! Here's some feedback: 

(very minor thing): 
- [ ] When the Sign In button is hover, the border should lighten
- [ ] I'd make clicking the "Start Uploading Today" button open the Sign Up modal

**Comment by evhumphrey** [comment]
- [ ] When clicking outside of the dropdown in your nav, it should close

**Comment by evhumphrey** [comment]
🎉
