### ISSUE TITLE
Song CRUD MVP

### ISSUE THREAD

**Issue by bmzhu2** [bmzhu2/StrifeCloud#3]
Have not finished update yet, but I figured I'd let you be able to see my progress due to my proposed schedule

**Comment by evhumphrey** [comment]
Some feedback based on what you have: 

- [ ] On the upload form, increase the top padding a tiny bit for the text area
- [ ] I would redirect to the track show page when song is uploaded

**Comment by evhumphrey** [comment]
Awesome, looks good! @bmzhu2 add some more songs (more seed data) and you'll be done :+1:
