### ISSUE TITLE
User Page

### ISSUE THREAD

**Issue by bmzhu2** [bmzhu2/StrifeCloud#6]
the wave things are just a static picture right now, everything else should be raring to go

**Comment by evhumphrey** [comment]
Cool, it looks like you've nearly finished your MVPs! Some feedback: 

- [ ] More seed data (more users)
- [ ] In the nav bar, the user profile image has a weird rough edge to it (see screenshots below). You can make it so their is no rough edge (look into using `overflow: hidden` and `object-fit: cover` -- let me know if you get stuck on this)

Rough edge: 
![Screen Shot 2019-05-09 at 11 40 29 AM](https://user-images.githubusercontent.com/6361824/57478316-71476d00-724f-11e9-838e-d8b62a50f546.png)

VS clean edge:
![Screen Shot 2019-05-09 at 11 40 42 AM](https://user-images.githubusercontent.com/6361824/57478373-9340ef80-724f-11e9-928a-f6f84a17bae6.png)

- [ ] Move the dropdown arrow and dots towards the center of navbar
![Screen Shot 2019-05-09 at 11 45 56 AM](https://user-images.githubusercontent.com/6361824/57478570-17937280-7250-11e9-8adb-a2bc15b4a23e.png)

- [ ] Show the number of tracks a user has (on the track show page, where it shows the user)
![Screen Shot 2019-05-09 at 11 31 31 AM](https://user-images.githubusercontent.com/6361824/57478607-35f96e00-7250-11e9-9f32-68582bfa93f0.png)

- [ ] On the right sidebar, replace ("ads here i guess" and "other songs") with something like the following: (you could also put a link to your linkedin and github here) 
![Screen Shot 2019-05-09 at 11 49 29 AM](https://user-images.githubusercontent.com/6361824/57478772-abfdd500-7250-11e9-90aa-1c19e6cfa52b.png)

**Comment by evhumphrey** [comment]
Also, you will be entering the BONUS stage soon, let me know if you have any questions
